# Site settings
title: Luca Palmieri
description: >
  Exploring the world of machine learning and deep learning through the lens of a
  young mathematician. "Learning Journal" is a place to collect think pieces, use-cases,
  examples and tutorial concerning artificial intelligence and machine learning at large.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukemathwalker.github.io" # the base hostname & protocol for your site

author:
  fullname: Luca Palmieri
  github: LukeMathWalker
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
